# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=135)),
            ],
            options={
                'db_table': 'Account_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_email', models.CharField(blank=True, max_length=135)),
                ('new_email', models.CharField(blank=True, max_length=135)),
                ('date', models.DateField(blank=True, null=True)),
                ('new_type', models.ForeignKey(blank=True, db_column='new_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_new', to='app_site.AccountType')),
                ('old_type', models.ForeignKey(blank=True, db_column='old_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_old', to='app_site.AccountType')),
            ],
            options={
                'db_table': 'Account_updates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=135)),
            ],
            options={
                'db_table': 'Categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disputes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, max_length=180)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Disputes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=135)),
            ],
            options={
                'db_table': 'Languages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Membership',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=135)),
            ],
            options={
                'db_table': 'Membership_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=180)),
                ('email', models.CharField(blank=True, max_length=135)),
                ('password', models.CharField(blank=True, max_length=135)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Password_reset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(blank=True, max_length=135)),
                ('in_favor_of', models.CharField(blank=True, max_length=135)),
                ('teensie_name', models.CharField(blank=True, max_length=135)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Payment_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfileUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=135)),
                ('last_name', models.CharField(blank=True, max_length=135)),
                ('city', models.CharField(blank=True, max_length=135)),
                ('country', models.CharField(blank=True, max_length=135)),
                ('date', models.DateField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Languages')),
            ],
            options={
                'db_table': 'Profile_updates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeensiesCancelled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=135)),
            ],
            options={
                'db_table': 'Teensies_cancelled',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeensiesDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Teensies_deleted',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeensiesFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Teensies_featured',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeensiesOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('released', models.CharField(blank=True, max_length=135)),
                ('review', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'Teensies_ordered',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeensiesPosted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teensie_name', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('timeframe', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, max_length=100)),
                ('ordered', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('featured', models.CharField(blank=True, max_length=135)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Categories')),
            ],
            options={
                'db_table': 'Teensies_posted',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=180, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=180)),
                ('facebook_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=180, unique=True)),
                ('password', models.CharField(blank=True, max_length=180)),
                ('date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=135)),
                ('country', models.CharField(blank=True, max_length=135)),
                ('image', models.CharField(blank=True, max_length=180)),
                ('cover', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('zip_code', models.CharField(blank=True, db_column='zip', max_length=180)),
                ('account_type', models.ForeignKey(blank=True, db_column='account_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.AccountType')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Languages')),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users')),
            ],
            options={
                'db_table': 'Users_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=300)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=135)),
                ('status', models.CharField(blank=True, max_length=135)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users')),
            ],
            options={
                'db_table': 'Withdrawal_requests',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='teensiesposted',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='teensiesordered',
            name='teensie',
            field=models.ForeignKey(blank=True, db_column='teensie', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.TeensiesPosted'),
        ),
        migrations.AddField(
            model_name='teensiesordered',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='teensiesfeatured',
            name='teensie',
            field=models.ForeignKey(blank=True, db_column='teensie', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.TeensiesPosted'),
        ),
        migrations.AddField(
            model_name='teensiesfeatured',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='teensiesdeleted',
            name='teensie',
            field=models.ForeignKey(blank=True, db_column='teensie', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.TeensiesPosted'),
        ),
        migrations.AddField(
            model_name='teensiescancelled',
            name='teensie',
            field=models.ForeignKey(blank=True, db_column='teensie', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.TeensiesPosted'),
        ),
        migrations.AddField(
            model_name='teensiescancelled',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='profileupdates',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='from_user',
            field=models.ForeignKey(blank=True, db_column='from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='to_user',
            field=models.ForeignKey(blank=True, db_column='to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(blank=True, db_column='membership_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.MembershipType'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='disputes',
            name='teensie',
            field=models.ForeignKey(blank=True, db_column='teensie', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.TeensiesPosted'),
        ),
        migrations.AddField(
            model_name='disputes',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_disp', to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='disputes',
            name='winner',
            field=models.ForeignKey(blank=True, db_column='winner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_disp', to='app_site.Users'),
        ),
        migrations.AddField(
            model_name='accountupdates',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.Users'),
        ),
    ]
